version: '3.5'
services:
  db:
    container_name: library_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=library_db
    image: postgres:16.1-alpine

  # настройки для pgAdmin
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: library@library.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"